# Generated by Django 3.1.2 on 2020-10-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='description_project',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='owner_project',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='reference_project',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='auth_parent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='description_project1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='description_project2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='owner_project1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='owner_project2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='project_goals1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='project_goals2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='reference_project1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='reference_project2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='score_project1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='score_project2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
