# Generated by Django 3.1.2 on 2020-10-07 05:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fake_api', '0002_auto_20201006_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='classroom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
